version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: scrutinizer/ocular
    versions:
    - 1.8.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uikit
    versions:
    - 3.6.14
    - 3.6.15
    - 3.6.16
    - 3.6.17
    - 3.6.18
    - 3.6.19
