---
kind: pipeline
type: docker
name: coding-standard-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.1-mariadb10.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.1-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.1-mysql5.7

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mysql
  pull: always
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.1-postgres9.4

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: postgres
    db_name: owncloud
    db_password: owncloud
    db_type: pgsql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: postgres
  pull: always
  image: postgres:9.4
  environment:
    POSTGRES_DB: owncloud
    POSTGRES_PASSWORD: owncloud
    POSTGRES_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.1-oracle

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: oracle
    db_name: XE
    db_password: oracle
    db_type: oci
    db_username: system
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: oracle
  pull: always
  image: owncloudci/oracle-xe:latest
  environment:
    ORACLE_DB: XE
    ORACLE_DISABLE_ASYNCH_IO: true
    ORACLE_PASSWORD: oracle
    ORACLE_USER: system

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.2-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.3-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/market

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/market
    version: daily-master-qa

- name: setup-server-market
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e market
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

depends_on:
- phpunit-php7.1-sqlite
- phpunit-php7.1-mariadb10.2
- phpunit-php7.1-mysql5.5
- phpunit-php7.1-mysql5.7
- phpunit-php7.1-postgres9.4
- phpunit-php7.1-oracle
- phpunit-php7.2-mysql5.5
- phpunit-php7.3-mysql5.5

...
