language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=market
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - nvm install --lts
  - composer install
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list

script:
  - ./occ app:enable market
  - cd apps/$APP_NAME/

  # Test the app
  - vendor/bin/parallel-lint --exclude vendor .
  - cd ../../
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then ../../lib/composer/bin/phpunit --configuration phpunit.xml; fi"

  # Create coverage report
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml; fi"

  # Build the app package
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then make clean dist; fi"

  # Run Javascript unit tests
#  - cd tests/js
#  - sh -c "if [ '$JSTESTS' = '1' ]; then npm install --deps; node_modules/karma/bin/karma start karma.config.js --single-run; fi"
#  - cd ../

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=mysql CORE_BRANCH=stable10
    - php: 7.1
      env: DB=mysql CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql CORE_BRANCH=master
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql;CODECHECK=1
    - php: 5.6
      env: DB=mysql;CODECHECK=2
  allow_failures:
    - env: DB=mysql;CODECHECK=1
    - env: DB=mysql;CODECHECK=2
  fast_finish: true
